services:
  postgres:
    image: postgres:17
    container_name: alpha_chat_db
    volumes:
      - ./schemas/dump.sql:/docker-entrypoint-initdb.d/dump.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: alpha_chat_redis
    volumes:
      - redis_data:/data
    networks:
      - backend
    restart: unless-stopped

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: alpha_chat_server
    depends_on:
      - postgres
      - redis
    networks:
      - backend
      - frontend
    restart: unless-stopped

  websockets:
    build:
      context: .
      dockerfile: websockets/Dockerfile
    container_name: alpha_chat_websockets
    depends_on:
      - redis
    networks:
      - backend
      - frontend
    restart: unless-stopped

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    container_name: alpha_chat_client
    depends_on:
      - server
      - websockets
    networks:
      - frontend
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  backend:
    driver: bridge
    internal: true
  frontend:
    driver: bridge
