services:
  postgres:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_prod_placeholder
      POSTGRES_DB: alpha_chat
    ports:
      - "5432:5432"

  redis:
    command: >
      redis-server
      --user admin on >prod_redis_pass_placeholder allcommands allkeys
    ports:
      - "6379:6379"

  server:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5126
      - ConnectionStrings__Default=Host=postgres;Port=5432;Database=alpha_chat;Username=postgres;Password=postgres_prod_placeholder
      - Redis__ConnectionString=redis:6379
      - CorsOrigins__0=https://alphachat.ivandev.cloud
      - Jwt__Key=prod-jwt-secret-placeholder
      - Jwt__Issuer=Production
      - Jwt__Audience=Backend
    ports:
      - "5126:5126"

  websockets:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5272
      - Redis__ConnectionString=redis:6379
      - CorsOrigins__0=https://alphachat.ivandev.cloud
    ports:
      - "5272:5272"

  client:
    build:
      args:
        BUILD_CONFIG: production
    ports:
      - "4003:4003"
