services:
  postgres:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_qas
      POSTGRES_DB: alpha_chat
    ports:
      - "5432:5432"
    volumes:
      - ./schemas/seed_qas.sql:/docker-entrypoint-initdb.d/zz_seed.sql

  redis:
    command: >
      redis-server
      --user admin on >qas_redis_pass allcommands allkeys
    ports:
      - "6379:6379"

  server:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5126
      - ConnectionStrings__Default=Host=postgres;Port=5432;Database=alpha_chat;Username=postgres;Password=postgres_qas
      - Redis__ConnectionString=redis:6379
      - CorsOrigins__0=https://qas-alphachat.ivandev.cloud
      - Jwt__Key=qas-jwt-secret-key
      - Jwt__Issuer=Development
      - Jwt__Audience=Backend
    ports:
      - "5126:5126"

  websockets:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5272
      - Redis__ConnectionString=redis:6379
      - CorsOrigins__0=https://qas-alphachat.ivandev.cloud
    ports:
      - "5272:5272"

  client:
    build:
      args:
        BUILD_CONFIG: development
    ports:
      - "4003:4003"
