name: Continuous Integration

on:
  pull_request:
    branches:
      - develop
      - release/**
      - main

  push:
    branches:
      - release/**
      - main

jobs:
  server-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        working-directory: server
        run: dotnet restore

      - name: Test
        working-directory: server
        run: dotnet test --no-restore --verbosity normal

  client-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install
        working-directory: client
        run: npm ci

      - name: Test
        working-directory: client
        run: npx ng test

  deploy-homolog:
    name: Deploy Homologação
    needs:
      - server-tests
      - client-tests

    if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/release/')

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: |
          curl --max-time 360 -s -X POST "${{ secrets.HOMOLOG_WEBHOOK_URL }}" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.WEBHOOK_AUTH_TOKEN }}" \
            -d '{
              "repository":"${{ github.repository }}",
              "branch":"${{ github.ref_name }}",
              "commit":"${{ github.sha }}"
            }'

  deploy-production:
    name: Deploy Produção
    needs:
      - server-tests
      - client-tests

    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: |
          curl --max-time 360 -s -X POST "${{ secrets.MAIN_WEBHOOK_URL }}" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.WEBHOOK_AUTH_TOKEN }}" \
            -d '{
              "repository":"${{ github.repository }}",
              "branch":"main",
              "commit":"${{ github.sha }}"
            }'
